### ISSUE TITLE
Monday - December 4th - at Shutterstock

### ISSUE THREAD

**Issue by RichardLitt** [nodeschool/montreal#65]
[Shutterstock](https://shutterstock.com/) is willing to host us on Monday, December 4th, starting from 5:30pm. Food will be provided 🎉 

Address is: 4398 St-Laurent st. #103

Mentors 
- arrive 10 minutes early, to connect with other mentors
- know the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) beforehand
- know elective workshoppers is good too :-)
- review [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page

Confirmed mentors:
- [ ] @CassieLR *
- [x] @matchai *
- [ ] @sophiedeziel
- [ ] @ziad-saab
- [x] @ajmas *
- [x] @ruyadorno 
- [ ] @fed135
- [ ] @ehren123
- [ ] @sayar 
- [ ] @shawnthompson
- [ ] @HarrisRobin
- [ ] @vicneanschi
- [ ] @pcuci *
- [x] @David-Ro *
- [x] @RichardLitt *
- [ ] @therazakhan
- [ ] @adelporte
- [ ] @jeffmarshall
- [ ] @nicolasgere
- [ ] @marekweb
- [ ] ___
- [ ] ___ (+ photographer role)
_*_ = also organizer/contributor

Anyone interested in coming? :)

**Comment by David-Ro** [comment]
I can arrange food like what you had Friday July 28th at meetup.com/Decentralized-Web-Montreal/                                                                                                                                                                                                                From: Richard LittauerSent: Tuesday, November 7, 2017 5:52 PMTo: nodeschool/montrealReply To: nodeschool/montrealCc: David Rowley 514; MentionSubject: [nodeschool/montreal] Monday - December 4th - at Shutterstock (#65)Shutterstock is willing to host us on Monday, December 4th. Still working on the food.
Address is still on St. Laurent in the Plateau. Exact location also forthcoming.
Mentors

arrive 10 minutes early, to connect with other mentors
know the core NodeSchool workshoppers beforehand
know elective workshoppers is good too :-)
review Mentor Best Practices wiki page

Confirmed mentors:

 @CassieLR *
 @matchai *
 @sophiedeziel
 @ziad-saab
 @ajmas *
 @ruyadorno
 @fed135
 @ehren123
 @sayar
 @shawnthompson
 @harrisrobin
 @vicneanschi
 @pcuci *
 @David-Ro *
 @RichardLitt *
 @therazakhan
 @adelporte
 @jeffmarshall
 @nicolasgere
 @marekweb
 ___
 ___ (+ photographer role)
* = also organizer/contributor

Anyone interested in coming? :)

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nodeschool/montreal","title":"nodeschool/montreal","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/nodeschool/montreal"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Monday - December 4th - at Shutterstock (#65)"}],"action":{"name":"View Issue","url":"https://github.com/nodeschool/montreal/issues/65"}}}

**Comment by fed135** [comment]
Food will be provided by Shutterstock (confirmed)
Doors will open at 5h30
Address is 4398 St-Laurent st. #103

**Comment by RichardLitt** [comment]
Thanks @David-Ro. Looks like @shutterstock has it covered. :)

**Comment by ajmas** [comment]
Just need create the Facebook event. Also update the website (opened ticket #72)

**Comment by RichardLitt** [comment]
@pcuci Can you help us with cross-posting on the relevant channels? I think you're the expert there.

**Comment by RichardLitt** [comment]
What a great event. Thanks all!
